site_name: BentoBox World
extra_css: [css/fullscreen.css, css/progressbar.css]
nav:
    - Home: index.md
    - FAQ: FAQ.md
    - Game Modes:
        - BSkyBlock: gamemodes/BSkyBlock/index.md
        - AcidIsland: gamemodes/AcidIsland/index.md
        - SkyGrid: gamemodes/SkyGrid/index.md
        - CaveBock: gamemodes/CaveBlock/index.md
        - AOneBlock: gamemodes/AOneBlock/index.md
    - Addons:
        - Biomes: addons/Biomes/index.md
        - Border: addons/Border/index.md
        - CauldronWitchery: addons/CauldronWitchery/index.md
        - Challenges: addons/Challenges/index.md
        - Chat: addons/Chat/index.md
        - CheckMeOut: addons/CheckMeOut/index.md
        - ControlPanel: addons/ControlPanel/index.md
        - DimensionalTrees: addons/DimensionalTrees/index.md
        - ExtraMobs: addons/ExtraMobs/index.md
        - Greenhouses: addons/Greenhouses/index.md
        - InvSwitcher: addons/InvSwitcher/index.md
        - IslandFly: addons/IslandFly/index.md
        - Level: addons/Level/index.md
        - Likes: addons/Likes/index.md
        - Limits: addons/Limits/index.md
        - MagicCobblestoneGenerator: addons/MagicCobblestoneGenerator/index.md
        - TwerkingForTrees: addons/TwerkingForTrees/index.md
        - VoidPortals: addons/VoidPortals/index.md
    - "Tutorials – Generic":
        - "Set a BentoBox world as the server's default world": BentoBox/Set-a-BentoBox-world-as-the-server-default-world.md
    - "Tutorials – API":
        - "Create an Addon": Tutorials/api/Create-an-addon.md
        - "Config API": BentoBox/Config-API.md
        - "Database API": BentoBox/Database-API.md
theme:
  name: readthedocs
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: "#"
